### ISSUE TITLE
ComboBox activated(int) does not get the index argument with PyQt5

### ISSUE THREAD

**Issue by ydirson** [CabbageDevelopment/qasync#3]
I have a python script doig the following:

```
class MainWindow(QQuickView):
    def __init__(self):
        ...
        self.screen1usageCombo = self.findChild(QtCore.QObject, "combo_screen1_usage")
        self.screen1usageCombo.activated.connect(self.change_screen1_mode)
...
    @asyncSlot()
    async def change_screen1_mode(self, index):
        ...
```

It works perfectly with Pyside2, but with PyQt5 (both 5.13.2 and 5.14.1) the result is:

```
Traceback (most recent call last):
  File "/home/yann/.local/lib/python3.7/site-packages/asyncqt/__init__.py", line 644, in wrapper
    asyncio.ensure_future(fn(*args, **kwargs))
TypeError: change_screen1_mode() missing 1 required positional argument: 'index'
Aborted
```

**Comment by TheGreatCabbage** [comment]
Thanks, I am able to reproduce this issue. I can also confirm that it is also present in `asyncqt`.

Strangely, in PyCharm the issue is only present when running normally; it is *not present* when using the debugger.

If anyone has any ideas about what's causing this behavior, comments are welcome!

**Comment by TheGreatCabbage** [comment]
Just to let you know, I'm busy at the moment but I should be able to look further into this in the next few weeks.

**Comment by syamajala** [comment]
I think you have to pass the type to the slot decorator, try this: @asyncSlot(object).

**Comment by TheGreatCabbage** [comment]
Thanks @syamajala! I can confirm that using `asyncSlot(int)` works fine in this case.

The fact that `asyncSlot()` alone works with PySide2 appears to be a case of undocumented behaviour; both PyQt5 and PySide2 expect data types to be supplied to their normal slots (`pyqtSlot` and `Slot` respectively), so it seems fair to follow the same standard with `asyncSlot` in `qasync`.

Since both PyQt5 and PySide2 work with `asyncSlot(object)`, I believe `qasync` is working as intended.

**Comment by ydirson** [comment]
Confirmed on my side as well!
